-- MySQL Script generated by MySQL Workbench
-- Mon Jun  1 16:04:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema citymis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema citymis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citymis` DEFAULT CHARACTER SET utf8 ;
USE `citymis` ;

-- -----------------------------------------------------
-- Table `citymis`.`basis_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`basis_student` (
  `id` BIGINT(18) NOT NULL COMMENT '主键',
  `study_id` VARCHAR(12) NOT NULL COMMENT '学号',
  `password` VARCHAR(12) NOT NULL COMMENT '密码（默认学号）',
  `salt` VARCHAR(32) NOT NULL COMMENT '盐加密',
  `name` VARCHAR(12) NOT NULL COMMENT '姓名',
  `gender` BIGINT(18) UNSIGNED NOT NULL COMMENT '性别（dic:1 男，0 女）',
  `profession` BIGINT(18) NOT NULL COMMENT '专业类别（FK）',
  `grade` VARCHAR(12) NOT NULL COMMENT '班级',
  `tel` VARCHAR(12) NOT NULL COMMENT '手机号码',
  `email` VARCHAR(16) NOT NULL COMMENT '电子邮箱',
  `people` BIGINT(18) NOT NULL COMMENT '名族类别(dic)',
  `political_status` BIGINT(18) NULL COMMENT '政治面貌类别(dic)',
  `id_card` VARCHAR(18) NOT NULL COMMENT '身份证号码',
  `home_town` VARCHAR(16) NOT NULL COMMENT '籍贯',
  `photo` VARCHAR(64) NULL COMMENT '照片（路径）',
  `gmt_admission` TIMESTAMP NOT NULL COMMENT '入学时间',
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `create_user_id` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP NOT NULL COMMENT '创建时间',
  `update_user_id` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间',
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_card_UNIQUE` (`id_card` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '系统模块-学生表';


-- -----------------------------------------------------
-- Table `citymis`.`basis_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`basis_teacher` (
  `id` BIGINT(18) NOT NULL COMMENT '主键',
  `work_id` VARCHAR(12) NOT NULL COMMENT '工号',
  `password` VARCHAR(12) NOT NULL COMMENT '密码（默认：工号）',
  `salt` VARCHAR(32) NOT NULL COMMENT '盐加密',
  `name` VARCHAR(12) NOT NULL COMMENT '姓名',
  `gender` BIGINT(18) UNSIGNED NOT NULL COMMENT '性别(dic: 1 表示男，0 表示女)',
  `college` BIGINT(18) NOT NULL COMMENT '院系类别（FK）',
  `tel` VARCHAR(12) NOT NULL COMMENT '手机号码',
  `landline` VARCHAR(12) NULL COMMENT '座机号码',
  `email` VARCHAR(16) NOT NULL COMMENT '电子邮箱',
  `people` BIGINT(18) UNSIGNED NOT NULL COMMENT '名族类别（dic）',
  `political_status` BIGINT(18) UNSIGNED NULL COMMENT '政治面貌类别（dic）',
  `id_card` VARCHAR(18) NOT NULL COMMENT '身份证号码',
  `home_town` VARCHAR(16) NOT NULL COMMENT '籍贯',
  `photo` VARCHAR(64) NULL COMMENT '照片路径',
  `education` BIGINT(18) UNSIGNED NOT NULL COMMENT '学历类别（dic）',
  `degree` BIGINT(18) UNSIGNED NOT NULL COMMENT '学位类别（dic）',
  `staff_type` BIGINT(18) NULL COMMENT '职工类别（dic）',
  `rank_type` BIGINT(18) NULL COMMENT '等级类别（dic）',
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `create_user_id` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP NOT NULL COMMENT '创建时间',
  `update_user_id` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间',
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC) VISIBLE,
  UNIQUE INDEX `landline_UNIQUE` (`landline` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `id_card_UNIQUE` (`id_card` ASC) VISIBLE,
  UNIQUE INDEX `work_id_UNIQUE` (`work_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`basis_college`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`basis_college` (
  `id` BIGINT(18) NOT NULL COMMENT '主键',
  `mark` VARCHAR(16) NOT NULL COMMENT '标识号',
  `name` VARCHAR(16) NOT NULL COMMENT '院系名称',
  `dean` BIGINT(18) NOT NULL COMMENT '院长（FK）',
  `contact` BIGINT(18) NOT NULL COMMENT '联系人（FK）',
  `sort` TINYINT(1) UNSIGNED NULL COMMENT '排序码',
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `create_user_id` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP NOT NULL COMMENT '创建时间',
  `update_user_id` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间',
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mark_UNIQUE` (`mark` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`basis_profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`basis_profession` (
  `id` BIGINT(18) NOT NULL,
  `mark` VARCHAR(16) NOT NULL COMMENT '标识号',
  `name` VARCHAR(16) NOT NULL COMMENT '专业名称',
  `dean` BIGINT(18) NOT NULL COMMENT '专业主任',
  `contact` BIGINT(18) NOT NULL COMMENT '联系人',
  `sort` TINYINT(1) UNSIGNED NULL COMMENT '排序码',
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `create_user_id` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP NOT NULL COMMENT '创建时间',
  `update_user_id` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间',
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mark_UNIQUE` (`mark` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_role` (
  `id` BIGINT(18) NOT NULL,
  `parent_id` BIGINT(18) NULL COMMENT '父id',
  `name` VARCHAR(32) NOT NULL COMMENT '角色名称',
  `description` VARCHAR(32) NOT NULL COMMENT '描述',
  `sort` TINYINT(1) UNSIGNED NULL COMMENT '排序码',
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `create_user_id` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP NOT NULL COMMENT '创建时间',
  `update_user_id` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间',
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_user_role` (
  `user_id` BIGINT(18) NOT NULL COMMENT '教师id',
  `role_id` BIGINT(18) NOT NULL COMMENT '角色id',
  PRIMARY KEY (`user_id`, `role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_authority` (
  `id` BIGINT(18) NOT NULL,
  `parent_id` BIGINT(18) NULL COMMENT '父id',
  `name` VARCHAR(32) NOT NULL COMMENT '权限名称',
  `mark` VARCHAR(32) NOT NULL COMMENT '权限标识',
  `description` VARCHAR(32) NOT NULL COMMENT '描述',
  `sort` TINYINT(1) UNSIGNED NULL COMMENT '排序码',
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `create_user_id` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP NOT NULL COMMENT '创建时间',
  `update_user_id` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间',
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_role_authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_role_authority` (
  `role_id` BIGINT(18) NOT NULL COMMENT '角色id',
  `authority_id` BIGINT(18) NOT NULL COMMENT '权限id',
  PRIMARY KEY (`role_id`, `authority_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_dictionary_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_dictionary_type` (
  `id` BIGINT(18) NOT NULL,
  `name` VARCHAR(16) NOT NULL COMMENT '字典类型名称',
  `type` VARCHAR(16) NOT NULL COMMENT '字典类型',
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `create_user_id` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP NOT NULL COMMENT '创建时间',
  `update_user_id` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间',
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_dictionary_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_dictionary_data` (
  `id` BIGINT(18) NOT NULL,
  `name` VARCHAR(16) NOT NULL COMMENT '字典数据名称',
  `value` TINYINT(1) NOT NULL COMMENT '键值',
  `type` BIGINT(18) NOT NULL COMMENT '字典类型（FK）',
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `create_user_id` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP NOT NULL COMMENT '创建时间',
  `update_user_id` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间',
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_user` (
  `id` BIGINT(18) NOT NULL,
  `account` VARCHAR(12) NOT NULL COMMENT '账号（学号、工号）',
  `password` VARCHAR(64) NOT NULL COMMENT '密码',
  `salt` VARCHAR(32) NOT NULL COMMENT '盐加密',
  `name` VARCHAR(12) NOT NULL COMMENT '登录名称（教师姓名、学生姓名）',
  `gender` TINYINT(1) NULL COMMENT '性别（1：男，0：女）',
  `tel` VARCHAR(12) NULL COMMENT '联系电话',
  `email` VARCHAR(16) NULL COMMENT '电子邮箱',
  `is_enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `create_user_id` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP NOT NULL COMMENT '创建时间',
  `update_user_id` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP NULL COMMENT '修改时间',
  `is_deleted` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC) VISIBLE,
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
