-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 20:59:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema citymis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema citymis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citymis` DEFAULT CHARACTER SET utf8 ;
USE `citymis` ;




-- -----------------------------------------------------
-- Table `citymis`.`system_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_role` (
  `id` BIGINT(18) NOT NULL,
  `parent_id` BIGINT(18) NULL COMMENT '父id',
  `name` VARCHAR(32) NOT NULL COMMENT '角色名称',
  `description` VARCHAR(32) NOT NULL COMMENT '描述',
  `sort` TINYINT(1) UNSIGNED NULL COMMENT '排序码',
  `is_enabled` BIGINT(18) UNSIGNED NOT NULL COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `creator` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP(6) NOT NULL COMMENT '创建时间',
  `updater` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP(6) NULL COMMENT '修改时间',
  `is_deleted` BIGINT(18) UNSIGNED NOT NULL COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_user_role` (
  `user_id` BIGINT(18) NOT NULL COMMENT '教师id',
  `role_id` BIGINT(18) NOT NULL COMMENT '角色id',
  PRIMARY KEY (`user_id`, `role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_authority` (
  `id` BIGINT(18) NOT NULL,
  `parent_id` BIGINT(18) NULL COMMENT '父id',
  `name` VARCHAR(32) NOT NULL COMMENT '权限名称',
  `mark` VARCHAR(32) NOT NULL COMMENT '权限标识',
  `description` VARCHAR(32) NOT NULL COMMENT '描述',
  `sort` TINYINT(1) UNSIGNED NULL COMMENT '排序码',
  `is_enabled` BIGINT(18) UNSIGNED NOT NULL COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `creator` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP(6) NOT NULL COMMENT '创建时间',
  `updater` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP(6) NULL COMMENT '修改时间',
  `is_deleted` BIGINT(18) UNSIGNED NOT NULL COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_role_authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_role_authority` (
  `role_id` BIGINT(18) NOT NULL COMMENT '角色id',
  `authority_id` BIGINT(18) NOT NULL COMMENT '权限id',
  PRIMARY KEY (`role_id`, `authority_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_dictionary_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_dictionary_type` (
  `id` BIGINT(18) NOT NULL,
  `name` VARCHAR(16) NOT NULL COMMENT '字典类型名称',
  `type` VARCHAR(16) NOT NULL COMMENT '字典类型',
  `is_enabled` BIGINT(18) UNSIGNED NOT NULL COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `creator` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP(6) NOT NULL COMMENT '创建时间',
  `updater` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP(6) NULL COMMENT '修改时间',
  `is_deleted` BIGINT(18) UNSIGNED NOT NULL COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_dictionary_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_dictionary_data` (
  `id` BIGINT(18) NOT NULL,
  `name` VARCHAR(16) NOT NULL COMMENT '字典数据名称',
  `value` TINYINT(1) NOT NULL COMMENT '键值',
  `type` BIGINT(18) NOT NULL COMMENT '字典类型（FK）',
  `is_enabled` BIGINT(18) UNSIGNED NOT NULL COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `creator` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP(6) NOT NULL COMMENT '创建时间',
  `updater` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP(6) NULL COMMENT '修改时间',
  `is_deleted` BIGINT(18) UNSIGNED NOT NULL COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citymis`.`system_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citymis`.`system_user` (
  `id` BIGINT(18) NOT NULL,
  `account` VARCHAR(12) NOT NULL COMMENT '账号（学号、工号）',
  `password` VARCHAR(12) NOT NULL COMMENT '密码',
  `salt` VARCHAR(32) NOT NULL COMMENT '盐加密',
  `name` VARCHAR(12) NOT NULL COMMENT '登录名称（教师姓名、学生姓名）',
  `gender` BIGINT(18) NULL COMMENT '性别',
  `tel` VARCHAR(12) NULL COMMENT '联系电话',
  `email` VARCHAR(16) NULL COMMENT '电子邮箱',
  `is_enabled` BIGINT(18) UNSIGNED NOT NULL COMMENT '启用标识（dic: 1 表示是，0 表示否）',
  `creator` BIGINT(18) NOT NULL COMMENT '创建者（FK）',
  `gmt_create` TIMESTAMP(6) NOT NULL COMMENT '创建时间',
  `updater` BIGINT(18) NULL COMMENT '修改者（FK）',
  `gmt_modified` TIMESTAMP(6) NULL COMMENT '修改时间',
  `is_deleted` BIGINT(18) UNSIGNED NOT NULL COMMENT '删除标识（ dic:1 表示是，0 表示否）',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
