@startuml
class Student{
-Long lId
-String cStudyId
-String cPassword
-String cName
-Integer nGender
-Long lProfession
-String cGrade
-String cTel
-String cEmail
-Integer nPeople
-Integer nPoliticalStatus
-String cIdCard
-String cHomeTown
-String cPhoto
-Date dAdmissionTime
-String cCreator
-Date dCreateTime
-String cUpdater
-Date dUpdateTime
toString()
}

@enduml
