@startuml
class Teacher{
-Long lId
-String cWorkId
-String cPassword
-String cName
-Integer nGender
-Long lCollege
-String cTel
-String cLandline
-String cEmail
-Integer nPeople
-Integer nPoliticalStatus
-String cIdCard
-String cHomeTown
-String cPhoto
-Integer nEducation
-Integer nDegree
-Integer nStaffType
-Integer nRankType
-String cCreator
-Date dCreateTime
-String cUpdater
-Date dUpdateTime
toString()
}

@enduml
